---
- name: Homework1 - Docker installation && nginx container
  hosts: all
  become: true
  
  # SET UP THE REPOSITORY
  tasks:
    - name: apt update
      apt: 
       update_cache: yes
       cache_valid_time: 3600

    - name: Install the prerequisites packages
      apt:
        pkg:
            - apt-transport-https
            - ca-certificates
            - curl
            - gnupg-agent
            - software-properties-common
    
    - name: Add the GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        
    - name: Add the Docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable #better use var here insted (ansible_distribution?)
        state: present

  # INSTALL DOCKER ENGINE - COMMUNITY
    - name: update apt's cache and install Docker
      apt: 
        update_cache: yes
        cache_valid_time: 3600
        pkg:
            - docker-ce
            - docker-ce-cli
            - containerd.io
      notify:
        - Restart Docker        
    
    - name: Add the user to the Docker group
      shell: usermod -aG docker ubuntu

    - name: Pull && Run nginx container
      shell: docker run -d -p 8080:80 nginx

      handlers:
      - name: Restart Docker
        ansible.builtin.service:
          name: docker
          state: restarted      
...