---
# Docker installation 
- name: update apt's cache and install Docker
  package:
    name:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - python3-pip
  notify:
    - RestartDocker

- name: Install docker-py
  pip:
    name: docker-py

# Add the user to docker's group 
- name: Add user to the Docker group
  user: 
    name: ubuntu
    group: docker
  when: ansible_pkg_mgr =='apt'

- name: Add user to the Docker group
  user: 
    name: ec2-user
    group: docker
  when: ansible_pkg_mgr =='dnf'
...